name: Tests

on:
  pull_request:
    branches:
      - main

env:
  # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
  COMPOSER_ROOT_VERSION: "dev-main"

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        actions:
          -
            name: 'Phpunit'
            run: composer phpunit

    name: ${{ matrix.actions.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      -   uses: actions/checkout@v3

      # see https://github.com/shivammathur/setup-php
      -
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      -   uses: "ramsey/composer-install@v1"

      -   run: ${{ matrix.actions.run }}
